### PR TITLE
Use the Lateset Pegasus Frontend apk over the Stable build

### PR DESCRIPTION
**Pull request by SoumyBhow**
This commit aims to replace the stable build of Pegasus with the latest version (As of today 2022-01-09). The reasoning is that the latest build is able to use (somewhat) URI paths, which are essential for emulators such as Dolphin, AetherSX2 and Citra MMJ while having little to no stability issues (at least in my experience). The {file.documenturi} property can be used in the metadata files to invoke URI paths. Of course, the old {file.path} can still be used without breaking anything.

This is my first pull request on Github, so I sincerely apologize if I missed some part of the pull request process or messed something up.

### CODE REVIEW

**Comment by dollerbill** [comment]
I like your reasoning to use the lastest build, but you'll also need to update this call on line 196

from `xdg-open ~/dragoonDoriseTools/pegasus-fe_alpha15-85-gfff1a5b2_android.apk` to `xdg-open ~/dragoonDoriseTools/pegasus-fe_alpha15-98-gf3dcfab5_android.apk`

**Review by dollerbill — CHANGES_REQUESTED** [review]
Need to also update the `xdg-open` call happening [here](https://github.com/dragoonDorise/pegasus-android-metadata/blob/311fe281ff2892cdb7300c7a37f6a86f6c4aecff/setup.sh#L196)

**Comment by SoumyBhow** [comment]
Okay, I believe I fixed it now. I'm not too fond of using the file name directly in the script but I'm nowhere near qualified enough to figure out a solution (at least for now). Hopefully, there's no issue with manually updating the script every time a new Pegasus version comes out...

**Comment by dragoonDorise** [comment]
Thanks ;)

**Pull request merged**
